[tool.poetry]
name = "llm-non-causal-ner"
version = "0.1.0"
description = ""
authors = ["Fred-Eric Kirsi <vegetablejuiceftw@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
transformers = "*"
datasets = "*"
torch = "*"
seqeval = "*"
accelerate = "*"
optimum = "*"
flash-attn = "*"
billm = "*"
peft = "*"
python-dotenv = {extras = ["cli"], version = "*"}
evaluate = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
